name: Deployment
on:
  push:
    branches:
      - main
      - dev

# Setting env variables for all jobs
# This env is setup as workflow level
env:
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    # Targetting specific environment,which may have different env variable values
    # NOTE:
    # If enviroment has protection rule, to only run if specific branch is target, even if workflow would be trigger by other branches, then the job targetting specific environment will not be run.
    environment: testing
    # This env is setup as job level
    env:
      #INFO:
      # Theproper way to project env data would be to set it up ask repository secrets like done here.
      MONGODB_CLUSTER_ADDRESS: cluster0.mcalwku.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080

    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        #Interpolating env variable in Linux/MacOS
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
